spring:
  application:
    name: spring-boot-sample-jetty
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    min-response-size: 1
  jetty:
    acceptors: -1
    selectors: -1
