spring:
  application:
    name: spring-boot-sample-logback
logging:
  # 指定日志配置文件位置
  config: classpath:logback-spring.xml
  # 指定日志文件路径
  path: /Users/fulgens/log
  file:
    # 指定日志文件大小超过配置大小进行归档处理
    max-size: 30MB
    # 指定日志文件保留天数
    max-history: 30