spring:
  application:
    name: spring-boot-sample-undertow
server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      dir: logs
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1
debug: true