spring:
  application:
    name: spring-boot-sample-simple
com:
  example:
    acme:
      enabled: true
      remote-address: 192.168.1.1
      security:
        username: admin
        password: 123456
        roles:
          - USER
          - ADMIN